### ISSUE TITLE
New lib version including the py.typed addition

### ISSUE THREAD

**Issue by humrochagf** [alexanderlukanin13/coolname#24]
Hello,

First of all thanks for this nice lib its quite handy, specially on naming builds and tests :slightly_smiling_face: 

I noticed that you added the `py.typed` file to the repo, but the latest published version of the lib doesn't have it yet.

I would be nice to have a new version of the lib pushed to pypi to be able to remove the ignore from mypy config.

And in case someone is using the lib with typehints active in your codebase you can skip it for now by adding this to your `pyproject.toml` file:

```toml
[[tool.mypy.overrides]]
module = [
  "coolname",
]
ignore_missing_imports = true
```
